#! /usr/bin/python3

from PyPDF2 import PdfFileMerger
import os 

DIRECTORY = './public/pdf_list/'

files = os.listdir(DIRECTORY)
files.remove('resume.pdf')
print(files)


files = ['resume.pdf'] + files
path = list(map(lambda filename: DIRECTORY + filename, files ))

merger = PdfFileMerger()

for pdf in path:
    merger.append(pdf)

merger.write("./public/Daniel's Resume.pdf")
